update_fastlane
fastlane_version "2.19.3"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")
    gym
    pilot

    # sh "your_script.sh"
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    # snapshot
    gym
    deliver(force: true)
    # frameit
    sh "telegram.sh"
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
