update_fastlane
fastlane_version "2.19.3"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")
    gym(scheme: "Controlio")
    pilot

    #sh "curl 'https://api.telegram.org/bot237463370:AAGI_aywb5T-oCyFaRHsgae5XhuEwWd257o/sendMessage?chat_id=-1001107091033&text=✈️ Controlio has been successfully deployed to the Test Flight!'"
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    snapshot
    gym(scheme: "Controlio")
    deliver(force: true)
    # frameit
    sh "curl 'https://api.telegram.org/bot237463370:AAGI_aywb5T-oCyFaRHsgae5XhuEwWd257o/sendMessage?chat_id=-1001107091033&text=🍎 Controlio has been successfully deployed to the AppStore!'"
  end

  desc "Deploy a new version to the App Store without screenshots"
  lane :releasens do
    match(type: "appstore")
    gym(scheme: "Controlio")
    deliver(force: true)
    # frameit
    sh "curl 'https://api.telegram.org/bot237463370:AAGI_aywb5T-oCyFaRHsgae5XhuEwWd257o/sendMessage?chat_id=-1001107091033&text=🍎 Controlio has been successfully deployed to the AppStore!'"
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
